### ISSUE TITLE
Please build latest pymssql for Python 3.10

### ISSUE THREAD

**Issue by rolweber** [ContinuumIO/anaconda-issues#13031]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other package requests and couldn't find a duplication

### Package info

pymssql
https://pypi.org/project/pymssql/#history

### Problem

When installing pymssql with Python 3.10, I get version 2.1.4 from Anaconda main.
The latest version on Anaconda main is 2.2.3, but this was only built for py39, py38, py37.
The latest version on PyPI is 2.2.5.

Please build a recent version of pymssql for Python 3.10 for all platforms, including linux-s390.

### Additional Context

`conda search pymssql=2` on linux-64:
```txt
Loading channels: done
# Name                       Version           Build  Channel             
pymssql                        2.1.4  py27h7b6447c_0  pkgs/main           
pymssql                        2.1.4 py310h7f8727e_0  pkgs/main           
pymssql                        2.1.4  py35h7b6447c_0  pkgs/main           
pymssql                        2.1.4  py36h7b6447c_0  pkgs/main           
pymssql                        2.1.4  py36h7f8727e_0  pkgs/main           
pymssql                        2.1.4  py37h7b6447c_0  pkgs/main           
pymssql                        2.1.4  py37h7f8727e_0  pkgs/main           
pymssql                        2.1.4  py38h7b6447c_0  pkgs/main           
pymssql                        2.1.4  py38h7f8727e_0  pkgs/main           
pymssql                        2.1.4  py39h7f8727e_0  pkgs/main           
pymssql                        2.1.5  py36h7b6447c_0  pkgs/main           
pymssql                        2.1.5  py37h7b6447c_0  pkgs/main           
pymssql                        2.1.5  py38h7b6447c_0  pkgs/main           
pymssql                        2.2.3  py37h7f8727e_0  pkgs/main           
pymssql                        2.2.3  py38h7f8727e_0  pkgs/main           
pymssql                        2.2.3  py39h7f8727e_0  pkgs/main           
```

**Comment by rolweber** [comment]
pymssql 2.1.4 is not compatible with Python 3.10, I get an import error:
```txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "src/pymssql.pyx", line 1, in init pymssql
  File "src/_mssql.pyx", line 48, in init _mssql
ImportError: cannot import name Iterable
```
pymssql 2.2.5 from PyPI works with Python 3.10.

**Comment by rolweber** [comment]
Interestingly, pymssql 2.2.3 has already been built for Python 3.10 on linux-ppc64le and linux-s390x.
But linux-64 is missing.
```txt
pymssql 2.2.3 py310h140841e_0
-----------------------------
file name   : pymssql-2.2.3-py310h140841e_0.conda
name        : pymssql
version     : 2.2.3
build       : py310h140841e_0
build number: 0
size        : 867 KB
license     : LGPL
subdir      : linux-ppc64le
url         : https://repo.anaconda.com/pkgs/main/linux-ppc64le/pymssql-2.2.3-py310h140841e_0.conda
md5         : 484d4db4a01c0818aa24521709be5dee
timestamp   : 2022-03-03 10:08:28 UTC
```

```txt
pymssql 2.2.3 py310h2a837d6_0
-----------------------------
file name   : pymssql-2.2.3-py310h2a837d6_0.conda
name        : pymssql
version     : 2.2.3
build       : py310h2a837d6_0
build number: 0
size        : 834 KB
license     : LGPL
subdir      : linux-s390x
url         : https://repo.anaconda.com/pkgs/main/linux-s390x/pymssql-2.2.3-py310h2a837d6_0.conda
md5         : 60f5483d044dd1d3d5a69390174d748c
timestamp   : 2022-01-31 09:17:49 UTC
dependencies: 
  - freetds >=1.3.3,<2.0a0
  - libgcc-ng >=7.5.0
  - python >=3.10,<3.11.0a0
```

**Comment by rolweber** [comment]
pymssql 2.2.5 is available now

Thank you!
