### ISSUE TITLE
Python build on OSX 10.12.6 with Xcode 9.2 fails

### ISSUE THREAD

**Issue by KaloyanP** [ContinuumIO/anaconda-issues#9040]
Hello,

I am trying to debug an issue with [segfaults when using GStreamer through PyGobject in conda](https://gitlab.gnome.org/GNOME/pygobject/issues/183). I have narrowed down the problem to only the anaconda and conda-forge Python binaries for OSX- it works everywhere else but on Python installed through conda on OSX. Interestingly, both the anaconda and conda-forge OSX builds use an old XCode compiler (60x ...), so I thought this was the likely culprit. However, when I try to build the anaconda Python recipe, it fails.
```
clang-4.0: warning: no such sysroot directory: '/opt/MacOSX10.9.sdk' [-Wmissing-sysroot]
```
Hacked away at it by changing the conda_build_config.yaml to have /Library/Developer/CommandLineTools/SDKs/ as the location of the MacOSX sdk, but I still get a failure:

```
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Users/kpashov/anaconda3/conda-bld/python_1522354442033/work/build-static/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Users/kpashov/anaconda3/conda-bld/python_1522354442033/work/build-static/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib
```

I have found that this is due to some "improvements" of the SDK added by Apple: https://trac.macports.org/ticket/54893

Anyway, how do I compile Python on my machine with a newer compiler? Alternatively, where in conda channels can I find a version of Python compiled with a slightly newer compiler so I can test if this is the issue?

### Steps to Reproduce
``` conda build anaconda3/pkgs/python-3.6.4-hc167b69_1/info/recipe/```
##### Anaconda or Miniconda version:
conda 4.5.0
conda-build 3.7.2

##### Operating System:
OSX 10.12.6
##### Clang version:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

##### `conda info`
```
active environment : k-gaze
    active env location : /Users/kpashov/anaconda3/envs/k-gaze
            shell level : 1
       user config file : /Users/kpashov/.condarc
 populated config files : /Users/kpashov/.condarc
          conda version : 4.5.0
    conda-build version : 3.7.2
         python version : 3.6.4.final.0
       base environment : /Users/kpashov/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/kpashov/anaconda3/pkgs
                          /Users/kpashov/.conda/pkgs
       envs directories : /Users/kpashov/anaconda3/envs
                          /Users/kpashov/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.4 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 1609668784:1741217763
             netrc file : None
           offline mode : False
```

##### `conda list --show-channel-urls`
```
# packages in environment at /Users/kpashov/anaconda3/envs/k-gaze:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0    conda-forge
AWSIoTPythonSDK           1.3.1                     <pip>
blas                      1.0                         mkl    conda-forge
boost                     1.59.0                   py36_0    menpo
boost-cpp                 1.64.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2018.1.18                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
cryptography              2.1.4                    py36_0    conda-forge
dlib                      19.4                     py36_0    menpo
ffmpeg                    3.2.4                         3    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gnutls                    3.5.17                        0    conda-forge
gobject-introspection     1.55.0                   py36_0    conda-forge
graphite2                 1.3.11                        0    conda-forge
harfbuzz                  1.7.1                         0    conda-forge
hdf5                      1.10.1                        2    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py36_1    conda-forge
intel-openmp              2018.0.0             h8158457_8    defaults
jasper                    1.900.1                       4    conda-forge
jpeg                      9b                            2    conda-forge
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    anaconda
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                          0    conda-forge
libidn11                  1.33                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libprotobuf               3.4.1                h326466f_0    defaults
libtiff                   4.0.9                         0    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxml2                   2.9.7                         0    conda-forge
mkl                       2018.0.1             hfbd8650_4    defaults
ncurses                   6.0                  hd04f020_2    defaults
nettle                    3.3                           0    conda-forge
numpy                     1.14.2           py36ha9ae307_0    defaults
openblas                  0.2.20                        7    conda-forge
openssl                   1.0.2n                        0    conda-forge
pcre                      8.41                          1    conda-forge
pip                       9.0.1            py36h1555ced_4    defaults
pixman                    0.34.0                        1    conda-forge
pycairo                   1.13.3                   py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
PyGObject                 3.28.2                    <pip>
pyopenssl                 17.5.0                   py36_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.3                         1    conda-forge
readline                  6.2                           2    defaults
requests                  2.18.4                   py36_1    conda-forge
setuptools                38.5.1                   py36_0    defaults
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
urllib3                   1.22                     py36_0    conda-forge
wheel                     0.30.0           py36h5eb2c71_1    defaults
x264                      20131217                      3    conda-forge
xz                        5.2.3                h0278029_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```

**Comment by mingwandroid** [comment]
> Interestingly, both the anaconda and conda-forge OSX builds use an old XCode compiler (60x ...), so I thought this was the likely culprit

Why do you say this? It is not the case. We build all of Anaconda Distribution using fairly modern custom built compilers on macOS and on Linux. On macOS they are built from upstream clang/llvm sources at version 4.0.1.

**Comment by mingwandroid** [comment]
I would advise you to stop trying to mix Homebrew software with Anaconda Distribution software too.

**Comment by KaloyanP** [comment]
Hi, I am saying this only because Python reported the following:
```
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

As for mixing shared libraries, Homebrew software, and conda - I would absolutely love to do have everything installed through conda. The main reason why we are trying to switch to conda is because it is supposed to be highly portable between OS-es, unlike a manually crafted combination of pip and virtualenv and a bunch of manually compiled binaries. The problem we have is that there are packages, such as the gstreamer-plugins-bad/ugly/good, that are not currently distributed or maintained through conda, but are well maintained through OS package managers. I know this is a hack, but in a small team we still can't invest the time to maintain those missing packages on conda,.

**Comment by mingwandroid** [comment]
> Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 

But this is a very old release of Python. If you run the latest you should see:

```
Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by mingwandroid** [comment]
Great. Conda-forge may be interested in gstreamer packages if you have time and were interested in contributing them? Closing as the original bug is just that two different eco-systems are incompatible and that's not a surprise.
