### ISSUE TITLE
ImportError: cannot import name 'Sequence' from 'collections'

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [ContinuumIO/anaconda-issues#13012]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.anaconda.com/) and didn't see anything to help

### What happened?

csvsql is a program that comes with csvkit package.  With python 3.10, it is failing with the following error:

```
$ csvsql -h
Traceback (most recent call last):
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\Scripts\csvsql-script.py", line 6, in <module>
    from csvkit.utilities.csvsql import launch_new_instance
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\csvkit\__init__.py", line 15, in <module>
    import agate
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\agate\__init__.py", line 5, in <module>
    from agate.aggregations import *
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\agate\aggregations\__init__.py", line 22, in <module>
    from agate.aggregations.count import Count  # noqa
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\agate\aggregations\count.py", line 5, in <module>
    from agate.utils import default
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\agate\utils.py", line 9, in <module>
    from collections import OrderedDict, Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Users\raju\.conda\envs\test_csvkit_py310\lib\collections\__init__.py)
```

The same command works with python 3.9 and prints the help page for csvsql.

Steps to reproduce the issue:
Consider the following two environment files
* env_test_csvkit_py310.yml - installs csvkit with python 3.10
* env_test_csvkit_py39.yml - installs csvkit with python 3.9

```
$ cat env_test_csvkit_py310.yml
name: test_csvkit_py310
channels:
  - defaults
dependencies:
  - python=3.10
  - csvkit

$ cat env_test_csvkit_py39.yml
name: test_csvkit_py39
channels:
  - defaults
dependencies:
  - python=3.9
  - csvkit
````
Create the test environments

```
$ conda env create -f env_test_csvkit_py310.yml
$ conda env create -f env_test_csvkit_py39.yml
````

Activate the test_csvkit_py310 environment and run the csvsql -h command to reproduce the issue.

```
$ conda activate test_csvkit_py310
$ csvsql -h
Traceback (most recent call last):
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\Scripts\csvsql-script.py", line 6, in <module>
    from csvkit.utilities.csvsql import launch_new_instance
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\csvkit\__init__.py", line 15, in <module>
    import agate
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\agate\__init__.py", line 5, in <module>
    from agate.aggregations import *
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\agate\aggregations\__init__.py", line 22, in <module>
    from agate.aggregations.count import Count  # noqa
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\agate\aggregations\count.py", line 5, in <module>
    from agate.utils import default
  File "C:\Users\raju\.conda\envs\test_csvkit_py310\lib\site-packages\agate\utils.py", line 9, in <module>
    from collections import OrderedDict, Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Users\raju\.conda\envs\test_csvkit_py310\lib\collections\__init__.py)
````

Do the same with test_csvkit_py39 to see the expected output

```
$ conda activate test_csvkit_py39
(test_csvkit_py39)
raju@DESKTOP-CRLPVE5 MINGW64 ~/work/github/rutils/python3/envs (master)
$ csvsql -h | head
usage: csvsql [-h] [-d DELIMITER] [-t] [-q QUOTECHAR] [-u {0,1,2,3}] [-b]
              [-p ESCAPECHAR] [-z FIELD_SIZE_LIMIT] [-e ENCODING] [-L LOCALE]
              [-S] [--blanks] [--date-format DATE_FORMAT]
              [--datetime-format DATETIME_FORMAT] [-H] [-K SKIP_LINES] [-v]
              [-l] [--zero] [-V]
              [-i {firebird,mssql,mysql,oracle,postgresql,sqlite,sybase}]
              [--db CONNECTION_STRING] [--query QUERY] [--insert]
              [--prefix PREFIX] [--before-insert BEFORE_INSERT]
              [--after-insert AFTER_INSERT] [--tables TABLE_NAMES]
              [--no-constraints] [--unique-constraint UNIQUE_CONSTRAINT]

````
The underlying issue is that test_csvkit_py310 pulls an old version of agate 1.6.1 while test_csvkit_py39 pulls a newer version of agate 1.6.2

```
$ conda list agate -n test_csvkit_py310
# packages in environment at C:\Users\raju\.conda\envs\test_csvkit_py310:
#
# Name                    Version                   Build  Channel
agate                     1.6.1           py310haa95532_2
agate-dbf                 0.2.2                      py_0
agate-excel               0.2.5              pyhd3eb1b0_0
agate-sql                 0.5.8              pyhd3eb1b0_0

$ conda list agate -n test_csvkit_py39
# packages in environment at C:\Users\raju\.conda\envs\test_csvkit_py39:
#
# Name                    Version                   Build  Channel
agate                     1.6.2            py39haa95532_2
agate-dbf                 0.2.2                      py_0
agate-excel               0.2.5              pyhd3eb1b0_0
agate-sql                 0.5.8              pyhd3eb1b0_0
```

### Conda info

```shell
$ conda info

     active environment : test_csvkit_py39
    active env location : C:\Users\raju\.conda\envs\test_csvkit_py39
            shell level : 3
       user config file : C:\Users\raju\.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Miniconda3  (read only)
      conda av data dir : C:\ProgramData\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\raju\.conda\pkgs
                          C:\Users\raju\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\raju\.conda\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\raju\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda config

```shell
<no output>
```

### Conda list

```shell
$ conda list --show-channel-urls
# packages in environment at C:\Users\raju\.conda\envs\test_csvkit_py310:
#
# Name                    Version                   Build  Channel
agate                     1.6.1           py310haa95532_2    defaults
agate-dbf                 0.2.2                      py_0    defaults
agate-excel               0.2.5              pyhd3eb1b0_0    defaults
agate-sql                 0.5.8              pyhd3eb1b0_0    defaults
babel                     2.9.1              pyhd3eb1b0_0    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2022.07.19           haa95532_0    defaults
certifi                   2022.6.15       py310haa95532_0    defaults
csvkit                    1.0.4           py310haa95532_0    defaults
dbfread                   2.0.7              pyhd3eb1b0_0    defaults
et_xmlfile                1.1.0           py310haa95532_0    defaults
greenlet                  1.1.1           py310hd77b12b_0    defaults
isodate                   0.6.0              pyhd3eb1b0_1    defaults
leather                   0.3.3           py310haa95532_0    defaults
libffi                    3.4.2                hd77b12b_4    defaults
olefile                   0.46               pyhd3eb1b0_0    defaults
openpyxl                  3.0.10          py310h2bbff1b_0    defaults
openssl                   1.1.1q               h2bbff1b_0    defaults
parsedatetime             2.4             py310haa95532_0    defaults
pip                       22.1.2          py310haa95532_0    defaults
python                    3.10.4               hbb2ffb3_0    defaults
python-slugify            5.0.2              pyhd3eb1b0_0    defaults
pytimeparse               1.1.8           py310haa95532_0    defaults
pytz                      2022.1          py310haa95532_0    defaults
setuptools                61.2.0          py310haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlalchemy                1.4.39          py310h2bbff1b_0    defaults
sqlite                    3.39.2               h2bbff1b_0    defaults
text-unidecode            1.3                pyhd3eb1b0_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
tzdata                    2022a                hda174b7_0    defaults
unidecode                 1.2.0              pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
wincertstore              0.2             py310haa95532_2    defaults
xlrd                      2.0.1              pyhd3eb1b0_0    defaults
xz                        5.2.5                h8cc25b3_1    defaults
zlib                      1.2.12               h8cc25b3_2    defaults
```

**Comment by KamarajuKusumanchi** [comment]
Per https://anaconda.org/anaconda/agate/files?version=1.7.1 , agate 1.7.1 was released to the 'defaults' channel on 2023-02-02.

**Comment by KamarajuKusumanchi** [comment]
I recreated the environments using the config files provided in the original bug report. Both env_test_csvkit_py310.yml and env_test_csvkit_py39.yml now pull agate 1.7.1. ``csvsql -h`` now works with both python version (3.10 and 3.9).

```
$ conda list agate -n test_csvkit_py310
...
# Name                    Version                   Build  Channel
agate                     1.7.1           py310haa95532_0    defaults
agate-dbf                 0.2.2                      py_0    defaults
agate-excel               0.2.5              pyhd3eb1b0_0    defaults
agate-sql                 0.5.8              pyhd3eb1b0_0    defaults

$ conda list agate -n test_csvkit_py39
...
# Name                    Version                   Build  Channel
agate                     1.7.1            py39haa95532_0    defaults
agate-dbf                 0.2.2                      py_0    defaults
agate-excel               0.2.5              pyhd3eb1b0_0    defaults
agate-sql                 0.5.8              pyhd3eb1b0_0    defaults
```

Closing the bug as the issue is resolved.
