### ISSUE TITLE
Cannot start Spyder because of "AttributeError: module 'pandas' has no attribute 'plotting' "

### ISSUE THREAD

**Issue by LindaSt** [ContinuumIO/anaconda-issues#1752]
I am working on Ubuntu 16.04 and have the anaconda 4.3.18 installed. I just update my packages with `conda updat --all` and now Spyder won't start anymore (starting it with `spyder` form the terminal). It throws the following error:

> Traceback (most recent call last):
  File "/home/linda/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/linda/anaconda3/lib/python3.5/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/linda/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 165, in <module>
    from spyder.utils.environ import WinUserEnvDialog
  File "/home/linda/anaconda3/lib/python3.5/site-packages/spyder/utils/environ.py", line 20, in <module>
    from spyder.widgets.variableexplorer.collectionseditor import CollectionsEditor
  File "/home/linda/anaconda3/lib/python3.5/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 46, in <module>
    from spyder.widgets.variableexplorer.importwizard import ImportWizard
  File "/home/linda/anaconda3/lib/python3.5/site-packages/spyder/widgets/variableexplorer/importwizard.py", line 26, in <module>
    import pandas as pd
  File "/home/linda/anaconda3/lib/python3.5/site-packages/pandas/__init__.py", line 51, in <module>
    plot_params = pandas.plotting._style._Options(deprecated=True)
AttributeError: module 'pandas' has no attribute 'plotting'

The currently installed version of pandas is 0.20.1.

Thanks!

COMMENT: Downgrading the pandas version to 0.19.2 fixed the issue, but I'd still like to be able to work with the new pandas version.

**Comment by ccordoba12** [comment]
This is caused by a bug in Pandas. I think it'll be fixed in its next release, so there's nothing we can do about it in the Spyder or Anaconda sides of things, sorry.

----

@mingwandroid, should we wait until a new release of Pandas is made before releasing Anaconda 4.4? Or at least not use 0.20.1 but 0.19.2 instead in our installers?
