### ISSUE TITLE
Cython Hello World Example works on Anacondas Python 3.3, but not 3.4

### ISSUE THREAD

**Issue by jsphon** [ContinuumIO/anaconda-issues#297]
I am using Anacondas on a 64-bit Windows machine.

I have compiled a hello world Cython example. It is in file hello.pyx, and contains:

```
def say_hello_to(name):
    print("Hello %s!" % name)
```

I am running it using run_hello.py

```
import pyximport; pyximport.install()
import hello as hello

hello.say_hello_to('jon')
```

The setup file is setup.py:

```
from distutils.core import setup
from Cython.Build import cythonize

setup(
  name = 'Hello world app',
  ext_modules = cythonize("hello.pyx"),
)
```

I am then compiling the code in Python 3.3 on Anacondas, using this code:

```
> activate py33
> python setup.py build_ext --inplace
```

( please note that py33 is my Python 3.3 environment )

I can then run the example:

```
python run_hello.py
```

which prints out "Hello jon!" as expected.

Now if I change my environment to Python 3.4 and compile:

```
> activate py34
> python setup.py build_ext --inplace
```

I get no error, and the shell displays

```
running build_ext
```

However, if I try to run run_hello.py from the py34 environment with:

```
python run_hello.py
```

I get:

```
Traceback (most recent call last):
  File "run_hello.py", line 2, in <module>
    import hello as hello
ImportError: DLL load failed: The specified module could not be found.
```

The error is not very descriptive. What could I do to help me make this work on Python 3.4?

---

If I delete hello.c and the /build folder from my hard drive, trying to compile from Python 3.4 returns:

```
Compiling hello.pyx because it changed.
Cythonizing hello.pyx
running build_ext
building 'hello' extension
creating build
creating build\temp.win-amd64-3.4
creating build\temp.win-amd64-3.4\Release
C:\Anaconda\envs\py34\Scripts\gcc.bat -mdll -O -Wall -IC:\Anaconda\envs\py34\include -IC:\Anaconda\envs\py34\include -c hello.c -o build\temp.win-amd64-3.4\Release\hello.o
writing build\temp.win-amd64-3.4\Release\hello.def
C:\Anaconda\envs\py34\Scripts\gcc.bat -shared -s build\temp.win-amd64-3.4\Release\hello.o build\temp.win-amd64-3.4\Release\hello.def -LC:\Anaconda\envs\py34\libs -LC:\Anaconda\envs\py34\PCbuild\amd64
-lpython34 -lmsvcr100 -o c:\Users\Jon\Documents\GitHub\CythonFunctions\example1\hello.pyd
build\temp.win-amd64-3.4\Release\hello.o:hello.c:(.text+0x314): undefined reference to `__imp__PyThreadState_Current'
build\temp.win-amd64-3.4\Release\hello.o:hello.c:(.text+0x493): undefined reference to `__imp__Py_NoneStruct'
build\temp.win-amd64-3.4\Release\hello.o:hello.c:(.text+0x97b): undefined reference to `__imp_PyExc_ImportError'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\Anaconda\\envs\\py34\\Scripts\\gcc.bat' failed with exit status 1
```

If I do the same with Python 3.3, I get:

```
Compiling hello.pyx because it changed.
Cythonizing hello.pyx
running build_ext
building 'hello' extension
creating build
creating build\temp.win-amd64-3.3
creating build\temp.win-amd64-3.3\Release
C:\Anaconda\envs\py33\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -IC:\Anaconda\envs\py33\include -IC:\Anaconda\envs\py33\include -c hello.c -o build\temp.win-amd64-3.3\Release\hello.o
writing build\temp.win-amd64-3.3\Release\hello.def
C:\Anaconda\envs\py33\Scripts\gcc.bat -DMS_WIN64 -shared -s build\temp.win-amd64-3.3\Release\hello.o build\temp.win-amd64-3.3\Release\hello.def -LC:\Anaconda\envs\py33\libs -LC:\Anaconda\envs\py33\PCb
uild\amd64 -lpython33 -lmsvcr100 -o c:\Users\Jon\Documents\GitHub\CythonFunctions\example1\hello.pyd
```

Some other users who experience the "gcc.bat failed with exit status 1" have found that the problem is due to 32/64 bit conflicts.

In the py33 version of the compilation data, there is -DMS_WIN64 in the gcc.bat parameters, but it is not in the py34 parameters. Could that be what is causing my issue? If so, how do I get py34 to add it?

**Comment by nehaljwani** [comment]
Closing as `Python 3.4` is no longer supported.
