### ISSUE TITLE
Build fails with gcc 7.3.0 when building two dependent projects

### ISSUE THREAD

**Issue by gabm** [ContinuumIO/anaconda-issues#10060]
## Actual Behavior

I have a project, that builds a shared lib and an executable that uses the lib on linux-64 using the defaults channel only. The lib privately depends on zmq but does not publish this dependency. The exe uses the lib by calling a function in it. Both are buil, installed and packaged in the same conda package.

After updating to gcc 7.3.0 the compilation of lib and exe succeeds but linking the exe throws an error that the dependency "libzmq" is not found:

```
/home/gabm/miniconda3/conda-bld/condatest_1536660221860/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libzmq.so.5, needed by libcondatestlib.so, not found (try using -rpath or -rpath-link)
/home/gabm/miniconda3/conda-bld/condatest_1536660221860/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: libcondatestlib.so: undefined reference to `zmq_ctx_shutdown'
/home/gabm/miniconda3/conda-bld/condatest_1536660221860/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: libcondatestlib.so: undefined reference to `zmq_ctx_new'
```

Doing the same while specifying gcc to be 7.2.0 works.

```
cxx_compiler_version:
  - 7.2.0 

c_compiler_version:
  - 7.2.0 
```

## Expected Behavior

It should work with 7.3.0 as well.

## Steps to Reproduce

- `clone https://github.com/gabm/condatest`
- `conda-build recipe`

**Comment by gabm** [comment]
The full build log with 7.3.0 is here: https://pastebin.com/4Shjqhf2

The full build log with 7.2.0 is here: https://pastebin.com/QuBM36CK

**Comment by mingwandroid** [comment]
You should add -Wl,-rpath-link,$PREFIX/lib to your LDFLAGS as advised.

**Comment by gabm** [comment]
@mingwandroid thank you so much for your fast answer! this seems to help indeed... could you please point me to where it is adviced?

stays 2 questions:

- why did it work in 7.2.0?
- the compiler seems to set LDFLAGS already to the _h_env, as seen here https://pastebin.com/4Shjqhf2 in line 126.. why doesn't this have any effect?

**Comment by mingwandroid** [comment]
It's not a bad question but I'm in vacation/holiday so the answer will have to wait. From my perspective I prefer being explicit by requiring that flag when necessary though.

**Comment by gabm** [comment]
Okay, thanks a lot.. enjoy your holiday :sun_with_face:

**Comment by mingwandroid** [comment]
Try adding -v to the compilation lines perhaps to see if you can figure it out. Call ld with -d (I think) too.

**Comment by gabm** [comment]
Just as a note what I did:

- I compared the linker lines after `make VERBOSE=1`, they are identical
- I compared the environment variables. The only differnence is `LDFLAGS`  now contains `--disable-new-dtags` ... I removed that flag but that didn't help.. Anyway, I googled a bit and found that this _might_ be the reason.. i don't fully understand it though..
- workaround (or intented behavior) is to set the `rpath-link` explicitly as mentioned above

**Comment by nehaljwani** [comment]
@gabm 7.2.0 depends on binutils 2.28.1 while 7.3.0 depends on binutils 2.31.1 . Between these two releases, a commit got introduced in binutils. More details about it here: https://sourceware.org/bugzilla/show_bug.cgi?id=23727

**Comment by gabm** [comment]
thank you for pointing me to that... seems like the reason for the behavior..

So from what i understand: 

- the binutils-linker does not search outside the sysroot anymore, in case it's specified
- the sysroot is expected to contain all the binaries runtime

When looking at conda, I think that the last point is not true. We have two different folders for that, right? Can we conclude that the LDFLAG: "-Wl,-rpath-link,$PREFIX/lib" is always needed in conda?

**Comment by mingwandroid** [comment]
> the binutils-linker does not search outside the sysroot anymore, in case it's specified

I don't think so, IFAIUI the `ld` now prepends `rpath` to `sysroot` when forming the automatically used `sysroot` `rpath-link` entry only.

> the sysroot is expected to contain all the binaries runtime

.. It is not modifying any `-rpath-link` options explicitly passed. but @nehaljwani will know better since he worked on this specific aspect.

> Can we conclude that the LDFLAG: "-Wl,-rpath-link,$PREFIX/lib" is always needed in conda?

I would rather not personally. I dislike passing flags that are not needed and that *could* be harmful (though I've not done a think through of whether it is particularly bad and I think some would rather we passed it; this may be one for a vote. My guiding principle on that what results in the least recipe text overall (eliding that flag vs adding it when needed). Flags should be applied minimally (though we pas a good few, they are reliable, high-performing, secure and very generally applicable).

We have 4 options as I see it:

1. Accept GCC developers opinion on this and keep their patch. I would rather not as we *do not want* anything in sysroot getting rpath-linked unless we are being very explicit about allowing some system libraries (enabled via CDT packages).
2. Revert the patch, I consider it incorrect. It's clearly a regression because GCC has always worked differently to this so the argument for us patch it out is not a bad one. Our compilers are pretty special and I get a feeling cross compilation isn't something GCC devs pay a lot of attention to unfortunately, but I do see their argument about RPATH-link.
3. Add it to the activation scripts; *may* break some things.
4. Add it to recipes on an as-needed basis.

I prefer 2 at present even if it goes against what Alan Modra's done in the code here.

**Comment by mingwandroid** [comment]
> while on 7.2.0 the --disable-new-dtags option is missing

Incorrect, -Wl,--disable-new-dtags has existed for many many years.

**Comment by mingwandroid** [comment]
I rebuilt the entire Python 3.7 stack (about 600 packages including C and C++ deps) and had to add -Wl,-rpath link about 5 times in total so I would be careful not to overstate the importance of this change.

**Comment by gabm** [comment]
hmm that might be true.. if it's so less frequent then i would be in favor of adding these flags when needed and accepting the upstream behavior..

**Comment by mingwandroid** [comment]
OK, thanks for the thoughtful feedback as always @gabm, I reckon we may want to put this to a conda-forge vote. If people want it added globally to activate then I'll accept that and we'll see if there's any fall out, otherwise my preference is to add it as needed too.

**Comment by nehaljwani** [comment]
>.. It is not modifying any -rpath-link options explicitly passed. but @nehaljwani will know better since he worked on this specific aspect.

Yes, that's correct. According to the mailing list thread which prompted the change in behaviour, they seem to have deliberately not touched -rpath-link:
> Leave -rpath-link unmodified, as build systems in the wild
are already using this to point to host directories.

I would also vote for option (1), unless a huge amount of repos start failing to build. I have only seen a handful of them so far.

Also, using `-Wl,-fuse-ld=gold` is also an option, since the gold linker is unaffected.
